// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ckvwevclnhtcnsdmashv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNrdndldmNsbmh0Y25zZG1hc2h2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NTc2NTgsImV4cCI6MjA2ODQzMzY1OH0.nGqUMAb2CZnVtz66Vc0kAU6nzpcT_7qrMgEi-AbqEsc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});